#pragma once

#define TGBM_ANSI_STR_HELPER(x) #x
#define TGBM_ANSI_STR(x) TGBM_ANSI_STR_HELPER(x)

#define TGBM_ANSI_COLOR(code) "\033[" TGBM_ANSI_STR(code) "m"

// styles
#define TGBM_ANSI_BOLD TGBM_ANSI_COLOR(1)
#define TGBM_ANSI_FAINT TGBM_ANSI_COLOR(2)
#define TGBM_ANSI_ITALIC TGBM_ANSI_COLOR(3)
#define TGBM_ANSI_UNDERLINE TGBM_ANSI_COLOR(4)
#define TGBM_ANSI_BLINK TGBM_ANSI_COLOR(5)
#define TGBM_ANSI_REVERSE TGBM_ANSI_COLOR(7)
#define TGBM_ANSI_HIDDEN TGBM_ANSI_COLOR(8)

// colors
#define TGBM_ANSI_BLACK TGBM_ANSI_COLOR(30)
#define TGBM_ANSI_RED TGBM_ANSI_COLOR(31)
#define TGBM_ANSI_GREEN TGBM_ANSI_COLOR(32)
#define TGBM_ANSI_YELLOW TGBM_ANSI_COLOR(33)
#define TGBM_ANSI_BLUE TGBM_ANSI_COLOR(34)
#define TGBM_ANSI_MAGENTA TGBM_ANSI_COLOR(35)
#define TGBM_ANSI_CYAN TGBM_ANSI_COLOR(36)
#define TGBM_ANSI_WHITE TGBM_ANSI_COLOR(37)

#define TGBM_ANSI_BRIGHT_BLACK TGBM_ANSI_COLOR(90)
#define TGBM_ANSI_BRIGHT_RED TGBM_ANSI_COLOR(91)
#define TGBM_ANSI_BRIGHT_GREEN TGBM_ANSI_COLOR(92)
#define TGBM_ANSI_BRIGHT_YELLOW TGBM_ANSI_COLOR(93)
#define TGBM_ANSI_BRIGHT_BLUE TGBM_ANSI_COLOR(94)
#define TGBM_ANSI_BRIGHT_MAGENTA TGBM_ANSI_COLOR(95)
#define TGBM_ANSI_BRIGHT_CYAN TGBM_ANSI_COLOR(96)
#define TGBM_ANSI_BRIGHT_WHITE TGBM_ANSI_COLOR(97)
#define TGBM_ANSI_RGB(R, G, B) \
  "\033[38;2;" TGBM_ANSI_STR(R) ";" TGBM_ANSI_STR(G) ";" TGBM_ANSI_STR(B) "m"

#define TGBM_ANSI_RESET "\033[0m"
